apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subsonic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subsonic-harmonia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: subsonic
  template:
    metadata:
      labels:
        app: subsonic
    spec:
      containers:
      - name: subsonic
        image: lasatou/subsonic:v1
        ports:
        - containerPort: 4040
        volumeMounts:
        - name: data
          mountPath: /var/subsonic
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: subsonic-pvc
